-- ==================================================================
-- Terrabovina — quem já esteve na equipa e já não está
-- ==================================================================
-- Aplica DEPOIS de schema_roles.sql (2), schema_auditoria.sql (14) e
-- schema_acesso_temporario.sql (15). Idempotente.
--
-- O PROBLEMA
--
-- Sair da equipa não deixava rasto NENHUM. Remover um trabalhador apagava a
-- linha de `membro_exploracao` e com ela tudo o que se sabia sobre a passagem
-- dele pela exploração: quando entrou, com que papel, quem o tirou e quando.
-- No dia seguinte, a pergunta "quem é que teve acesso a isto em março?" não
-- tinha onde ser respondida — e o registo de atividade (`schema_atividade.sql`)
-- também não responde: ele guarda o que a pessoa FEZ, não que ela cá esteve.
--
-- Isto conta duas vezes:
--
--   · Numa exploração a sério passa gente. O veterinário de uma visita, o
--     ajudante de uma campanha. Meses depois, a lista de quem cá anda não diz
--     nada sobre quem cá andou.
--   · É a metade que falta à auditoria. O registo mostra "o Joaquim alterou o
--     terreno das Fontes a 3 de março"; sem isto não há onde ver que o Joaquim
--     entrou a 1 de março e saiu a 12.
--
-- A ESCOLHA: TABELA À PARTE, E NÃO UMA MARCA NA LINHA
--
-- A saída podia ficar marcada em `membro_exploracao` (uma coluna `saiu_em`,
-- como o `estado` do animal em `schema_auditoria.sql`). Não fica, de propósito.
--
-- Essa linha é o que DÁ ACESSO: passa pelos três ajudantes por onde toda a RLS
-- da base decide o que cada um vê e escreve (`membro_de`, `role_em`,
-- `pode_cap`). Uma coluna nova obrigava a repetir a condição "e ainda não saiu"
-- nos três, e esquecê-la num deles deixava um trabalhador removido a ler — ou a
-- escrever — uma exploração de que já foi posto fora. É o mesmo tipo de erro
-- que o prazo de acesso quase cometeu (ver o cabeçalho do 15).
--
-- Assim, a remoção continua a ser um `delete` — o acesso acaba pelo caminho de
-- sempre, sem uma condição nova em lado nenhum — e o que se guarda é uma CÓPIA
-- do que a linha dizia, noutra tabela, que não dá acesso a coisa nenhuma.
--
-- O NOME FICA AQUI GRAVADO
--
-- E não vai buscar-se ao perfil na altura de mostrar, como o resto da app faz:
-- o `nomes_da_equipa()` (14) só devolve quem é membro AGORA, precisamente por
-- ser essa a única brecha aberta na RLS do `perfil`. Quem saiu deixaria de ter
-- nome — e um histórico de gente sem nome não é histórico nenhum. Fica a cópia
-- do nome à hora da saída, que é também o que estava certo naquele dia.
-- ==================================================================


-- ------------------------------------------------------------------
-- 1. A tabela
-- ------------------------------------------------------------------
create table if not exists public.equipa_historico (
  id bigint generated by default as identity primary key,
  -- Sem `references public.exploracao`: a exploração pode ser apagada mais
  -- tarde, e o `on delete cascade` levava o histórico atrás. Que é o contrário
  -- do que uma tabela destas serve.
  exploracao_id text not null,
  -- `on delete set null`: apagar a conta de alguém não apaga o registo de que
  -- ele trabalhou na exploração de OUTRA pessoa. O nome, esse, sai — ver o
  -- gatilho de RGPD lá em baixo.
  user_id uuid references auth.users (id) on delete set null,
  -- O nome à hora da saída (ver o cabeçalho).
  nome text not null default 'Sem nome',
  role public.role_membro not null,
  entrou_em timestamptz,
  saiu_em timestamptz not null default now(),
  saiu_por uuid references auth.users (id) on delete set null,
  -- `removido` = alguém o tirou da equipa. `saiu` = tirou-se a si próprio.
  -- Duas frases diferentes no ecrã, e a diferença interessa a quem lê.
  motivo text not null default 'removido' check (motivo in ('removido', 'saiu'))
);

-- É sempre lido da mesma maneira: uma exploração, do mais recente para trás.
create index if not exists idx_equipa_historico_exploracao
  on public.equipa_historico (exploracao_id, saiu_em desc);
create index if not exists idx_equipa_historico_user
  on public.equipa_historico (user_id);


-- ------------------------------------------------------------------
-- 2. Quem pode ler
-- ------------------------------------------------------------------
-- Quem gere a exploração vê quem lá passou. Cada pessoa vê as SUAS passagens —
-- pela mesma razão do registo de atividade: quem não vê o que lhe diz respeito
-- não consegue perceber o que aconteceu à conta dele.
alter table public.equipa_historico enable row level security;

drop policy if exists equipa_historico_select on public.equipa_historico;
create policy equipa_historico_select on public.equipa_historico
  for select using (
    public.eh_superadmin()
    or user_id = auth.uid()
    or public.role_em(exploracao_id) = 'admin'
  );

-- Escrever é só do gatilho, que corre como dono da função e passa por cima da
-- RLS. Sem estes `revoke`, qualquer sessão podia inventar (ou apagar) saídas —
-- e um histórico que o próprio pode reescrever vale menos do que nenhum,
-- porque parece de fiar.
revoke insert, update, delete on public.equipa_historico from anon, authenticated;
grant select on public.equipa_historico to authenticated;


-- ------------------------------------------------------------------
-- 3. O gatilho
-- ------------------------------------------------------------------
create or replace function public.registar_saida_da_equipa()
returns trigger language plpgsql security definer set search_path = 'public' as $$
declare
  o_nome text;
begin
  -- A exploração inteira foi apagada, e isto é a cascata a limpar os membros.
  -- Escrever aqui uma saída por pessoa enchia o histórico de linhas sobre uma
  -- exploração que já não existe e que ninguém tem onde ver.
  if not exists (select 1 from public.exploracao where id = old.exploracao_id) then
    return null;
  end if;

  -- A CONTA da pessoa foi apagada, e isto é a cascata a limpar os vínculos
  -- dela. Guardar-lhe o nome aqui era manter dados pessoais de alguém que
  -- exerceu o direito ao apagamento (ver schema_rgpd.sql) — e o nome é o que
  -- esta tabela guarda de propósito. Nesse caso não se escreve nada.
  if not exists (select 1 from auth.users where id = old.user_id) then
    return null;
  end if;

  select coalesce(nullif(btrim(p.nome), ''), 'Sem nome')
    into o_nome
    from public.perfil p
   where p.id = old.user_id;

  insert into public.equipa_historico
    (exploracao_id, user_id, nome, role, entrou_em, saiu_por, motivo)
  values (
    old.exploracao_id,
    old.user_id,
    coalesce(o_nome, 'Sem nome'),
    old.role,
    old.criado_em,
    auth.uid(),
    -- Quem se remove a si próprio SAIU; a toda a gente o resto foi removido.
    case when auth.uid() = old.user_id then 'saiu' else 'removido' end
  );

  return null;   -- gatilho AFTER: o valor devolvido é ignorado
exception when others then
  -- REGRA DA CASA, a mesma do registo de atividade: o que serve para OBSERVAR
  -- o trabalho nunca pode impedir o trabalho. Um erro a escrever o histórico
  -- não pode deixar o dono sem conseguir remover alguém da equipa.
  raise warning 'Saída da equipa não registada (% de %): %',
    old.user_id, old.exploracao_id, sqlerrm;
  return null;
end;
$$;

drop trigger if exists membro_regista_saida on public.membro_exploracao;
create trigger membro_regista_saida
  after delete on public.membro_exploracao
  for each row execute function public.registar_saida_da_equipa();


-- ------------------------------------------------------------------
-- 4. Apagar a conta apaga também o nome nas saídas dos outros
-- ------------------------------------------------------------------
-- O `on delete set null` do `user_id` corta a ligação à conta, mas o NOME
-- continuava escrito na coluna — que é exatamente o dado pessoal que o
-- apagamento tinha de levar. Fica um gatilho em `auth.users` a limpá-lo.
--
-- O histórico não desaparece: o dono da exploração continua a ver que naquele
-- dia saiu um trabalhador, com que papel e quando entrou. Deixa é de saber
-- quem era, que é o que a lei pede.
create or replace function public.esquecer_nome_no_historico()
returns trigger language plpgsql security definer set search_path = 'public' as $$
begin
  update public.equipa_historico
     set nome = 'Conta apagada'
   where user_id = old.id;
  return old;
exception when others then
  raise warning 'Nome não limpo no histórico da equipa (%): %', old.id, sqlerrm;
  return old;
end;
$$;

-- BEFORE, e não AFTER: depois do `delete` o `on delete set null` já correu e
-- não há um único `user_id` por onde encontrar as linhas desta pessoa.
drop trigger if exists utilizador_esquece_nome_historico on auth.users;
create trigger utilizador_esquece_nome_historico
  before delete on auth.users
  for each row execute function public.esquecer_nome_no_historico();


-- ------------------------------------------------------------------
-- Tabela nova: a API tem de reler o schema
-- ------------------------------------------------------------------
notify pgrst, 'reload schema';


-- ------------------------------------------------------------------
-- VERIFICAR
-- ------------------------------------------------------------------
-- 1. Remover alguém da equipa escreve uma linha, com nome e data de entrada:
--
--   delete from public.membro_exploracao where id = '<id do vínculo>';
--   select exploracao_id, nome, role, entrou_em, saiu_em, motivo
--     from public.equipa_historico order by saiu_em desc limit 5;
--
-- 2. Apagar a exploração NÃO escreve uma linha por membro (a cascata é calada):
--
--   -- contar antes e depois de apagar uma exploração de teste com equipa;
--   -- a contagem tem de ficar igual
--   select count(*) from public.equipa_historico;
--
-- 3. Ninguém consegue escrever à mão (tem de dar "permission denied"):
--
--   insert into public.equipa_historico (exploracao_id, role)
--   values ('<exploracao>', 'trabalhador');
--
-- 4. Um trabalhador não vê as saídas dos outros. Na sessão dele:
--
--   select count(*) from public.equipa_historico;   -- só as linhas dele
