-- ==================================================================
-- Terrabovina — o registo de quem alterou o quê, e quando
-- ==================================================================
-- Aplica DEPOIS de schema_permissoes.sql (13), schema_auditoria.sql (14) e
-- schema_acesso_temporario.sql (15). Idempotente.
--
-- O PROBLEMA
--
-- O dono passou a poder dar acesso à sua exploração a trabalhadores e a
-- veterinários. Passou também a não ter forma nenhuma de saber o que é que eles
-- lá fizeram. Um animal com a data de parto mudada, um terreno renomeado, uma
-- despesa lançada — tudo aparece como se tivesse acontecido sozinho.
--
-- Isto não é desconfiança: é a pergunta prática de quem chega ao fim do dia e
-- vê um número diferente do que deixou de manhã. Sem resposta, a saída é não
-- dar acesso a ninguém, e a app perde metade do que promete.
--
-- O QUE FICA REGISTADO
--
-- Uma linha por alteração em `animal`, `evento`, `terreno` e `movimento`: quem,
-- quando, em que exploração, e uma frase que diz o que foi. Escrita por
-- TRIGGER, nunca pelo cliente — numa app offline-first o telemóvel decide o que
-- envia, e um registo em que o registado escolhe o autor não regista nada.
--
-- O QUE **NÃO** FICA
--
-- O valor antigo de cada campo. Guardar o antes e o depois de tudo dava um
-- histórico completo e uma tabela que cresce mais depressa do que os dados —
-- e a pergunta a que isto responde ("quem lá mexeu, e quando") não precisa
-- dele. O que aconteceu a um animal em concreto continua a ver-se no histórico
-- dele.
--
-- PORQUÊ NÃO SÓ PARA A EQUIPA
--
-- Regista-se toda a gente, incluindo o dono. Filtrar por papel dentro do
-- trigger obrigaria a decidir no servidor uma coisa que muda (hoje o dono é
-- admin, amanhã há dois donos), e um registo com buracos é pior do que nenhum:
-- quem o lê não sabe se a linha não existe porque não houve alteração, ou
-- porque o autor não era dos que se registam. A app é que escolhe o que mostra.
-- ==================================================================


-- ------------------------------------------------------------------
-- 1. A tabela
-- ------------------------------------------------------------------
create table if not exists public.registo_atividade (
  id bigint generated by default as identity primary key,
  em timestamptz not null default now(),
  exploracao_id text not null,
  -- `on delete set null`: apagar a conta de um trabalhador não pode apagar o
  -- registo do que ele fez na exploração de outra pessoa.
  user_id uuid references auth.users (id) on delete set null,
  tabela text not null check (tabela in ('animal', 'evento', 'terreno', 'movimento')),
  registo_id text,
  acao text not null check (acao in ('criou', 'alterou', 'removeu')),
  -- A frase legível ("Vaca 'Malhada'", "Despesa de 120 € em ração"). Montada no
  -- trigger, onde a linha ainda está à mão: montá-la depois obrigava a ir
  -- buscar um animal que pode já não existir.
  resumo text not null default ''
);

-- É sempre lido da mesma maneira: uma exploração, do mais recente para trás.
create index if not exists idx_atividade_exploracao_em
  on public.registo_atividade (exploracao_id, em desc);
create index if not exists idx_atividade_user on public.registo_atividade (user_id);


-- ------------------------------------------------------------------
-- 2. Quem pode ler
-- ------------------------------------------------------------------
-- Quem gere a exploração vê tudo o que lá se passou. Cada pessoa vê o que ela
-- própria fez — não por transparência simétrica, mas porque um trabalhador que
-- não vê o que registou não consegue perceber se o que fez ficou gravado.
alter table public.registo_atividade enable row level security;

drop policy if exists atividade_select on public.registo_atividade;
create policy atividade_select on public.registo_atividade
  for select using (
    public.eh_superadmin()
    or user_id = auth.uid()
    or public.role_em(exploracao_id) = 'admin'
  );

-- Escrever é só do trigger, que corre como dono da função e passa por cima da
-- RLS. Sem estes `revoke`, qualquer sessão podia inserir linhas — ou seja,
-- escrever no registo de auditoria as alterações que quisesse, em nome de quem
-- quisesse. Um registo assim vale menos do que nada, porque parece de fiar.
revoke insert, update, delete on public.registo_atividade from anon, authenticated;
grant select on public.registo_atividade to authenticated;


-- ------------------------------------------------------------------
-- 3. O trigger
-- ------------------------------------------------------------------
-- Uma só função para as quatro tabelas: o que muda entre elas é onde está a
-- exploração e como se lê a linha em português, e isso resolve-se com o
-- `tg_table_name`. Quatro funções quase iguais era garantir que uma ficava para
-- trás na próxima alteração.
create or replace function public.registar_atividade()
returns trigger language plpgsql security definer set search_path = 'public' as $$
declare
  linha        record;
  exp_id       text;
  quem         uuid := auth.uid();
  o_que        text;
  qual_acao    text;
begin
  -- Sem sessão não há autor. É o caso dos scripts de manutenção e das
  -- reparações corridas no SQL Editor: registá-las como alterações de ninguém
  -- enchia a lista do criador com linhas que ele não consegue explicar.
  if quem is null then
    return null;
  end if;

  -- `if` e não `case`: o PL/pgSQL não aceita dois registos de tipos diferentes
  -- nos dois ramos de um `case`, mesmo quando são a mesma tabela.
  if tg_op = 'DELETE' then linha := old; else linha := new; end if;

  -- Uma sincronização que reenvia a linha tal e qual (a app offline-first
  -- reenvia a fila inteira quando a rede volta) não é uma alteração. Sem esta
  -- guarda, cada regresso de rede escrevia dezenas de linhas a dizer que nada
  -- mudou.
  if tg_op = 'UPDATE'
     and (to_jsonb(new) - 'updated_at') = (to_jsonb(old) - 'updated_at') then
    return null;
  end if;

  qual_acao := case tg_op when 'INSERT' then 'criou' when 'DELETE' then 'removeu' else 'alterou' end;

  if tg_table_name = 'animal' then
    exp_id := linha.exploracao_id;
    o_que := coalesce(
      nullif(btrim(linha.nome), ''),
      nullif(btrim(linha.numero_identificacao), ''),
      'animal sem nome'
    );
    -- Tirar do efetivo é um `update` do estado (ver schema_auditoria.sql), e
    -- lê-lo como "alterou" escondia justamente a alteração que mais interessa.
    if tg_op = 'UPDATE'
       and new.estado is distinct from old.estado
       and coalesce(new.estado, 'ativo') <> 'ativo' then
      qual_acao := 'removeu';
      o_que := o_que || ' (' || coalesce(new.estado, 'saída') || ')';
    end if;

  elsif tg_table_name = 'terreno' then
    exp_id := linha.exploracao_id;
    o_que := coalesce(nullif(btrim(linha.nome), ''), 'terreno sem nome');

  elsif tg_table_name = 'movimento' then
    exp_id := linha.exploracao_id;
    o_que := case linha.direcao when 'receita' then 'Receita' else 'Despesa' end
             || ' de ' || trim(to_char(linha.valor, 'FM999G999G990D00')) || ' €'
             || coalesce(' · ' || nullif(btrim(linha.categoria), ''), '');

  elsif tg_table_name = 'evento' then
    -- O evento não tem exploração: pertence a um animal, e é o animal que a
    -- tem. Sem o animal (apagado a sério nalgum ponto do passado) não há onde
    -- pendurar a linha, e mais vale não escrever nada do que escrever uma
    -- linha que ninguém consegue ver.
    select a.exploracao_id,
           coalesce(nullif(btrim(a.nome), ''), nullif(btrim(a.numero_identificacao), ''), 'animal')
      into exp_id, o_que
      from public.animal a
     where a.id = linha.animal_id;
    if exp_id is null then
      return null;
    end if;
    o_que := coalesce(nullif(btrim(linha.tipo), ''), 'registo') || ' · ' || o_que;

  else
    return null;
  end if;

  if exp_id is null then
    return null;
  end if;

  insert into public.registo_atividade (exploracao_id, user_id, tabela, registo_id, acao, resumo)
  values (exp_id, quem, tg_table_name, linha.id::text, qual_acao, left(o_que, 200));

  return null;   -- AFTER trigger: o valor devolvido é ignorado
exception when others then
  -- REGRA DA CASA, a mesma do aviso de registo: o que serve para OBSERVAR o
  -- trabalho nunca pode impedir o trabalho. Um erro a escrever a auditoria
  -- deixaria o criador sem conseguir gravar um animal, e sem perceber porquê.
  raise warning 'Registo de atividade não escrito (% em %): %', tg_op, tg_table_name, sqlerrm;
  return null;
end;
$$;

drop trigger if exists animal_regista_atividade on public.animal;
create trigger animal_regista_atividade
  after insert or update or delete on public.animal
  for each row execute function public.registar_atividade();

drop trigger if exists terreno_regista_atividade on public.terreno;
create trigger terreno_regista_atividade
  after insert or update or delete on public.terreno
  for each row execute function public.registar_atividade();

drop trigger if exists evento_regista_atividade on public.evento;
create trigger evento_regista_atividade
  after insert or update or delete on public.evento
  for each row execute function public.registar_atividade();

-- O `movimento` pode não existir: as finanças nascem no schema_financas.sql
-- (8) e há bases antigas onde este ficheiro pode correr antes de alguém as
-- ligar. Sem o `if exists`, o ficheiro inteiro rebentava por causa da tabela
-- que falta, e os outros três triggers não chegavam a ser criados.
do $$
begin
  if to_regclass('public.movimento') is not null then
    drop trigger if exists movimento_regista_atividade on public.movimento;
    create trigger movimento_regista_atividade
      after insert or update or delete on public.movimento
      for each row execute function public.registar_atividade();
  else
    raise notice 'Tabela movimento não existe: registo de atividade das finanças não instalado.';
  end if;
end $$;


-- ------------------------------------------------------------------
-- 4. Limpeza
-- ------------------------------------------------------------------
-- O registo cresce para sempre e ninguém pergunta o que aconteceu há dois anos.
-- Não há `pg_cron` no plano grátis, por isso isto não corre sozinho: fica à
-- mão para quando a tabela incomodar (`select public.limpar_atividade_antiga();`).
create or replace function public.limpar_atividade_antiga(dias int default 365)
returns bigint language plpgsql security definer set search_path = 'public' as $$
declare
  apagadas bigint;
begin
  if not public.eh_superadmin() then
    raise exception 'apenas o superadmin pode limpar o registo de atividade';
  end if;
  delete from public.registo_atividade where em < now() - make_interval(days => dias);
  get diagnostics apagadas = row_count;
  return apagadas;
end;
$$;


-- ------------------------------------------------------------------
-- Tabela nova: a API tem de reler o schema
-- ------------------------------------------------------------------
notify pgrst, 'reload schema';


-- ------------------------------------------------------------------
-- VERIFICAR
-- ------------------------------------------------------------------
-- 1. Uma alteração a um animal escreve uma linha com o autor certo:
--
--   update public.animal set nome = nome || ' ' where id = '<id>';
--   select em, tabela, acao, resumo, user_id from public.registo_atividade
--    order by em desc limit 5;
--
-- 2. Reenviar a MESMA linha não escreve nada (é o caso da sincronização):
--
--   update public.animal set updated_at = now() where id = '<id>';
--   -- a contagem de linhas do registo tem de ficar igual
--
-- 3. Um trabalhador vê só o que ele próprio fez; o dono vê tudo. Na sessão do
--    trabalhador:
--
--   select count(*) from public.registo_atividade;
--
-- 4. Ninguém consegue escrever à mão no registo (tem de dar "permission denied"):
--
--   insert into public.registo_atividade (exploracao_id, tabela, acao)
--   values ('<exploracao>', 'animal', 'criou');
